//! Material definitions — 17 sheet materials + 6 CNC materials.

use serde::{Deserialize, Serialize};

/// Material identifier (e.g. "al5052", "ss304", "mild_steel")
pub type MaterialId = String;

/// Physical material properties for rendering and simulation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PhysicalMaterial {
    pub id: MaterialId,
    pub name: String,
    pub group: MaterialGroup,
    pub density_g_per_cm3: f64,
    pub yield_strength_mpa: f64,
    pub tensile_strength_mpa: f64,
    pub elastic_modulus_gpa: f64,
    pub hardness_bhn: Option<f64>,
    pub thermal_conductivity_w_per_mk: f64,
    pub specific_heat_j_per_kg_k: f64,
    pub melting_point_c: f64,
}

/// Material groups
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MaterialGroup {
    Aluminum,
    Steel,
    Stainless,
    Titanium,
    CopperBrass,
    Composites,
    Plastics,
    Rubber,
}

/// Sheet material with thickness options
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SheetMaterial {
    pub id: MaterialId,
    pub name: String,
    pub group: MaterialGroup,
    pub available_thicknesses_in: Vec<f64>,
    pub density_g_per_cm3: f64,
    pub yield_strength_mpa: f64,
    pub tensile_strength_mpa: f64,
    pub elastic_modulus_gpa: f64,
    pub hardness_bhn: Option<f64>,
    pub thermal_conductivity_w_per_mk: f64,
    pub specific_heat_j_per_kg_k: f64,
    /// Laser cutting material factor
    pub laser_k_factor: f64,
    /// Plasma cutting material factor
    pub plasma_k_factor: f64,
    /// Waterjet cutting material factor
    pub waterjet_k_factor: f64,
    /// K-factor for bend allowance
    pub bend_k_factor: f64,
}

/// CNC material with machinability properties
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CncMaterial {
    pub id: MaterialId,
    pub name: String,
    pub density_g_per_cm3: f64,
    pub yield_strength_mpa: f64,
    pub tensile_strength_mpa: f64,
    pub elastic_modulus_gpa: f64,
    pub hardness_bhn: f64,
    pub machinability: Machinability,
    /// Kienzle specific cutting force kc1.1 (N/mm²)
    pub kc11: f64,
    /// Kienzle exponent mc
    pub mc: f64,
    /// Taylor tool life constant C
    pub taylor_c: f64,
    /// Taylor exponent n
    pub taylor_n: f64,
    pub thermal_conductivity_w_per_mk: f64,
}

/// Machinability rating
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Machinability {
    Excellent,
    Good,
    Moderate,
    Difficult,
    VeryDifficult,
}

/// Appearance properties for rendering
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Appearance {
    pub base_color: [f32; 4],     // RGBA
    pub metallic: f32,             // 0.0 - 1.0
    pub roughness: f32,            // 0.0 - 1.0
    pub emission: [f32; 3],        // RGB emission
    pub opacity: f32,              // 0.0 - 1.0
}

impl Default for Appearance {
    fn default() -> Self {
        Self {
            base_color: [0.7, 0.7, 0.7, 1.0],
            metallic: 0.5,
            roughness: 0.4,
            emission: [0.0; 3],
            opacity: 1.0,
        }
    }
}

/// Build the default catalog of 17 sheet materials
pub fn default_sheet_materials() -> Vec<SheetMaterial> {
    vec![
        SheetMaterial {
            id: "al5052".into(),
            name: "Aluminum 5052-H32".into(),
            group: MaterialGroup::Aluminum,
            available_thicknesses_in: vec![0.032, 0.040, 0.050, 0.063, 0.080, 0.090, 0.100, 0.125, 0.160, 0.190, 0.250],
            density_g_per_cm3: 2.68,
            yield_strength_mpa: 193.0,
            tensile_strength_mpa: 228.0,
            elastic_modulus_gpa: 70.3,
            hardness_bhn: Some(60.0),
            thermal_conductivity_w_per_mk: 138.0,
            specific_heat_j_per_kg_k: 880.0,
            laser_k_factor: 1.0,
            plasma_k_factor: 1.1,
            waterjet_k_factor: 0.9,
            bend_k_factor: 0.33,
        },
        SheetMaterial {
            id: "al6061".into(),
            name: "Aluminum 6061-T6".into(),
            group: MaterialGroup::Aluminum,
            available_thicknesses_in: vec![0.040, 0.050, 0.063, 0.080, 0.090, 0.100, 0.125, 0.160, 0.190, 0.250],
            density_g_per_cm3: 2.71,
            yield_strength_mpa: 276.0,
            tensile_strength_mpa: 310.0,
            elastic_modulus_gpa: 68.9,
            hardness_bhn: Some(95.0),
            thermal_conductivity_w_per_mk: 167.0,
            specific_heat_j_per_kg_k: 896.0,
            laser_k_factor: 1.0,
            plasma_k_factor: 1.1,
            waterjet_k_factor: 0.9,
            bend_k_factor: 0.33,
        },
        SheetMaterial {
            id: "al7075".into(),
            name: "Aluminum 7075-T6".into(),
            group: MaterialGroup::Aluminum,
            available_thicknesses_in: vec![0.040, 0.050, 0.063, 0.080, 0.090, 0.100, 0.125, 0.160, 0.190],
            density_g_per_cm3: 2.81,
            yield_strength_mpa: 503.0,
            tensile_strength_mpa: 572.0,
            elastic_modulus_gpa: 71.7,
            hardness_bhn: Some(150.0),
            thermal_conductivity_w_per_mk: 130.0,
            specific_heat_j_per_kg_k: 960.0,
            laser_k_factor: 1.0,
            plasma_k_factor: 1.05,
            waterjet_k_factor: 0.95,
            bend_k_factor: 0.33,
        },
        SheetMaterial {
            id: "mild_steel".into(),
            name: "Mild Steel A36".into(),
            group: MaterialGroup::Steel,
            available_thicknesses_in: vec![0.030, 0.036, 0.048, 0.060, 0.075, 0.105, 0.120, 0.135, 0.187, 0.250, 0.375, 0.500],
            density_g_per_cm3: 7.85,
            yield_strength_mpa: 250.0,
            tensile_strength_mpa: 400.0,
            elastic_modulus_gpa: 200.0,
            hardness_bhn: Some(119.0),
            thermal_conductivity_w_per_mk: 51.9,
            specific_heat_j_per_kg_k: 486.0,
            laser_k_factor: 0.8,
            plasma_k_factor: 1.0,
            waterjet_k_factor: 1.0,
            bend_k_factor: 0.42,
        },
        SheetMaterial {
            id: "ar500".into(),
            name: "AR500 Armor Steel".into(),
            group: MaterialGroup::Steel,
            available_thicknesses_in: vec![0.188, 0.250, 0.375, 0.500],
            density_g_per_cm3: 7.85,
            yield_strength_mpa: 1400.0,
            tensile_strength_mpa: 1600.0,
            elastic_modulus_gpa: 205.0,
            hardness_bhn: Some(500.0),
            thermal_conductivity_w_per_mk: 42.0,
            specific_heat_j_per_kg_k: 480.0,
            laser_k_factor: 0.5,
            plasma_k_factor: 0.7,
            waterjet_k_factor: 0.6,
            bend_k_factor: 0.45,
        },
        SheetMaterial {
            id: "spring_1075".into(),
            name: "Spring Steel 1075".into(),
            group: MaterialGroup::Steel,
            available_thicknesses_in: vec![0.015, 0.020, 0.025, 0.032, 0.040, 0.050, 0.063, 0.080, 0.100, 0.125],
            density_g_per_cm3: 7.85,
            yield_strength_mpa: 480.0,
            tensile_strength_mpa: 690.0,
            elastic_modulus_gpa: 205.0,
            hardness_bhn: Some(200.0),
            thermal_conductivity_w_per_mk: 49.0,
            specific_heat_j_per_kg_k: 486.0,
            laser_k_factor: 0.7,
            plasma_k_factor: 0.85,
            waterjet_k_factor: 0.85,
            bend_k_factor: 0.40,
        },
        SheetMaterial {
            id: "steel_1095".into(),
            name: "High Carbon 1095".into(),
            group: MaterialGroup::Steel,
            available_thicknesses_in: vec![0.025, 0.032, 0.040, 0.050, 0.063, 0.080, 0.100, 0.125],
            density_g_per_cm3: 7.87,
            yield_strength_mpa: 525.0,
            tensile_strength_mpa: 980.0,
            elastic_modulus_gpa: 205.0,
            hardness_bhn: Some(293.0),
            thermal_conductivity_w_per_mk: 45.0,
            specific_heat_j_per_kg_k: 486.0,
            laser_k_factor: 0.65,
            plasma_k_factor: 0.80,
            waterjet_k_factor: 0.80,
            bend_k_factor: 0.42,
        },
        SheetMaterial {
            id: "ss304_sheet".into(),
            name: "Stainless 304".into(),
            group: MaterialGroup::Stainless,
            available_thicknesses_in: vec![0.024, 0.030, 0.036, 0.048, 0.060, 0.075, 0.105, 0.120, 0.135, 0.187, 0.250],
            density_g_per_cm3: 8.00,
            yield_strength_mpa: 215.0,
            tensile_strength_mpa: 505.0,
            elastic_modulus_gpa: 193.0,
            hardness_bhn: Some(123.0),
            thermal_conductivity_w_per_mk: 16.2,
            specific_heat_j_per_kg_k: 500.0,
            laser_k_factor: 0.6,
            plasma_k_factor: 0.8,
            waterjet_k_factor: 0.85,
            bend_k_factor: 0.45,
        },
        SheetMaterial {
            id: "ss316_sheet".into(),
            name: "Stainless 316L".into(),
            group: MaterialGroup::Stainless,
            available_thicknesses_in: vec![0.030, 0.036, 0.048, 0.060, 0.075, 0.105, 0.120, 0.135, 0.187, 0.250],
            density_g_per_cm3: 8.00,
            yield_strength_mpa: 170.0,
            tensile_strength_mpa: 485.0,
            elastic_modulus_gpa: 193.0,
            hardness_bhn: Some(217.0),
            thermal_conductivity_w_per_mk: 14.6,
            specific_heat_j_per_kg_k: 500.0,
            laser_k_factor: 0.55,
            plasma_k_factor: 0.75,
            waterjet_k_factor: 0.80,
            bend_k_factor: 0.45,
        },
        SheetMaterial {
            id: "ti_grade2".into(),
            name: "Titanium Grade 2".into(),
            group: MaterialGroup::Titanium,
            available_thicknesses_in: vec![0.020, 0.025, 0.032, 0.040, 0.050, 0.063, 0.080, 0.100, 0.125],
            density_g_per_cm3: 4.51,
            yield_strength_mpa: 275.0,
            tensile_strength_mpa: 345.0,
            elastic_modulus_gpa: 103.0,
            hardness_bhn: Some(145.0),
            thermal_conductivity_w_per_mk: 16.4,
            specific_heat_j_per_kg_k: 523.0,
            laser_k_factor: 0.45,
            plasma_k_factor: 0.6,
            waterjet_k_factor: 0.7,
            bend_k_factor: 0.38,
        },
        SheetMaterial {
            id: "ti_grade5".into(),
            name: "Titanium Grade 5".into(),
            group: MaterialGroup::Titanium,
            available_thicknesses_in: vec![0.032, 0.040, 0.050, 0.063, 0.080, 0.100, 0.125, 0.160, 0.190],
            density_g_per_cm3: 4.43,
            yield_strength_mpa: 880.0,
            tensile_strength_mpa: 950.0,
            elastic_modulus_gpa: 114.0,
            hardness_bhn: Some(334.0),
            thermal_conductivity_w_per_mk: 6.7,
            specific_heat_j_per_kg_k: 560.0,
            laser_k_factor: 0.40,
            plasma_k_factor: 0.55,
            waterjet_k_factor: 0.65,
            bend_k_factor: 0.38,
        },
        SheetMaterial {
            id: "copper_110".into(),
            name: "Copper 110".into(),
            group: MaterialGroup::CopperBrass,
            available_thicknesses_in: vec![0.021, 0.025, 0.032, 0.040, 0.050, 0.063, 0.080, 0.100, 0.125],
            density_g_per_cm3: 8.94,
            yield_strength_mpa: 69.0,
            tensile_strength_mpa: 221.0,
            elastic_modulus_gpa: 117.0,
            hardness_bhn: Some(40.0),
            thermal_conductivity_w_per_mk: 391.0,
            specific_heat_j_per_kg_k: 385.0,
            laser_k_factor: 0.35,
            plasma_k_factor: 0.6,
            waterjet_k_factor: 0.9,
            bend_k_factor: 0.35,
        },
        SheetMaterial {
            id: "brass_260".into(),
            name: "Brass 260".into(),
            group: MaterialGroup::CopperBrass,
            available_thicknesses_in: vec![0.025, 0.032, 0.040, 0.050, 0.063, 0.080, 0.100, 0.125],
            density_g_per_cm3: 8.53,
            yield_strength_mpa: 124.0,
            tensile_strength_mpa: 338.0,
            elastic_modulus_gpa: 110.0,
            hardness_bhn: Some(65.0),
            thermal_conductivity_w_per_mk: 120.0,
            specific_heat_j_per_kg_k: 380.0,
            laser_k_factor: 0.40,
            plasma_k_factor: 0.65,
            waterjet_k_factor: 0.85,
            bend_k_factor: 0.35,
        },
        SheetMaterial {
            id: "carbon_fiber".into(),
            name: "Carbon Fiber".into(),
            group: MaterialGroup::Composites,
            available_thicknesses_in: vec![0.020, 0.032, 0.040, 0.063, 0.080, 0.100, 0.125],
            density_g_per_cm3: 1.60,
            yield_strength_mpa: 600.0,
            tensile_strength_mpa: 3500.0,
            elastic_modulus_gpa: 230.0,
            hardness_bhn: None,
            thermal_conductivity_w_per_mk: 17.0,
            specific_heat_j_per_kg_k: 710.0,
            laser_k_factor: 0.9,
            plasma_k_factor: 0.0, // Not recommended
            waterjet_k_factor: 1.2,
            bend_k_factor: 0.0, // Not bendable
        },
        SheetMaterial {
            id: "acrylic_clear".into(),
            name: "Clear Acrylic".into(),
            group: MaterialGroup::Plastics,
            available_thicknesses_in: vec![0.060, 0.080, 0.100, 0.125, 0.187, 0.250, 0.375, 0.500],
            density_g_per_cm3: 1.18,
            yield_strength_mpa: 72.0,
            tensile_strength_mpa: 75.0,
            elastic_modulus_gpa: 3.1,
            hardness_bhn: None,
            thermal_conductivity_w_per_mk: 0.19,
            specific_heat_j_per_kg_k: 1470.0,
            laser_k_factor: 1.5,
            plasma_k_factor: 0.0, // Not recommended
            waterjet_k_factor: 1.3,
            bend_k_factor: 0.0, // Heat-bent, different process
        },
        SheetMaterial {
            id: "polycarbonate".into(),
            name: "Polycarbonate".into(),
            group: MaterialGroup::Plastics,
            available_thicknesses_in: vec![0.060, 0.080, 0.100, 0.125, 0.187, 0.250],
            density_g_per_cm3: 1.20,
            yield_strength_mpa: 62.0,
            tensile_strength_mpa: 70.0,
            elastic_modulus_gpa: 2.4,
            hardness_bhn: None,
            thermal_conductivity_w_per_mk: 0.20,
            specific_heat_j_per_kg_k: 1250.0,
            laser_k_factor: 0.5, // Tends to melt
            plasma_k_factor: 0.0,
            waterjet_k_factor: 1.4,
            bend_k_factor: 0.0,
        },
        SheetMaterial {
            id: "neoprene".into(),
            name: "Neoprene Rubber".into(),
            group: MaterialGroup::Rubber,
            available_thicknesses_in: vec![0.063, 0.125, 0.187, 0.250],
            density_g_per_cm3: 1.23,
            yield_strength_mpa: 3.0,
            tensile_strength_mpa: 10.0,
            elastic_modulus_gpa: 0.01,
            hardness_bhn: None,
            thermal_conductivity_w_per_mk: 0.19,
            specific_heat_j_per_kg_k: 2100.0,
            laser_k_factor: 0.0, // Fire hazard
            plasma_k_factor: 0.0,
            waterjet_k_factor: 1.5,
            bend_k_factor: 0.0,
        },
    ]
}

/// Build the default catalog of 6 CNC materials
pub fn default_cnc_materials() -> Vec<CncMaterial> {
    vec![
        CncMaterial {
            id: "al6061".into(),
            name: "Aluminum 6061-T6".into(),
            density_g_per_cm3: 2.71,
            yield_strength_mpa: 276.0,
            tensile_strength_mpa: 310.0,
            elastic_modulus_gpa: 68.9,
            hardness_bhn: 95.0,
            machinability: Machinability::Excellent,
            kc11: 800.0,
            mc: 0.25,
            taylor_c: 350.0,
            taylor_n: 0.28,
            thermal_conductivity_w_per_mk: 167.0,
        },
        CncMaterial {
            id: "al7075".into(),
            name: "Aluminum 7075-T6".into(),
            density_g_per_cm3: 2.81,
            yield_strength_mpa: 503.0,
            tensile_strength_mpa: 572.0,
            elastic_modulus_gpa: 71.7,
            hardness_bhn: 150.0,
            machinability: Machinability::Good,
            kc11: 900.0,
            mc: 0.25,
            taylor_c: 300.0,
            taylor_n: 0.26,
            thermal_conductivity_w_per_mk: 130.0,
        },
        CncMaterial {
            id: "ss304".into(),
            name: "Stainless 304".into(),
            density_g_per_cm3: 8.00,
            yield_strength_mpa: 215.0,
            tensile_strength_mpa: 505.0,
            elastic_modulus_gpa: 193.0,
            hardness_bhn: 123.0,
            machinability: Machinability::Moderate,
            kc11: 2100.0,
            mc: 0.26,
            taylor_c: 120.0,
            taylor_n: 0.20,
            thermal_conductivity_w_per_mk: 16.2,
        },
        CncMaterial {
            id: "steel1018".into(),
            name: "Steel 1018".into(),
            density_g_per_cm3: 7.87,
            yield_strength_mpa: 370.0,
            tensile_strength_mpa: 440.0,
            elastic_modulus_gpa: 205.0,
            hardness_bhn: 126.0,
            machinability: Machinability::Good,
            kc11: 1700.0,
            mc: 0.25,
            taylor_c: 200.0,
            taylor_n: 0.22,
            thermal_conductivity_w_per_mk: 51.9,
        },
        CncMaterial {
            id: "ti64".into(),
            name: "Titanium 6Al-4V".into(),
            density_g_per_cm3: 4.43,
            yield_strength_mpa: 880.0,
            tensile_strength_mpa: 950.0,
            elastic_modulus_gpa: 114.0,
            hardness_bhn: 334.0,
            machinability: Machinability::Difficult,
            kc11: 1500.0,
            mc: 0.23,
            taylor_c: 60.0,
            taylor_n: 0.15,
            thermal_conductivity_w_per_mk: 6.7,
        },
        CncMaterial {
            id: "pom".into(),
            name: "POM/Delrin".into(),
            density_g_per_cm3: 1.41,
            yield_strength_mpa: 69.0,
            tensile_strength_mpa: 78.0,
            elastic_modulus_gpa: 3.1,
            hardness_bhn: 20.0,
            machinability: Machinability::Excellent,
            kc11: 200.0,
            mc: 0.30,
            taylor_c: 800.0,
            taylor_n: 0.35,
            thermal_conductivity_w_per_mk: 0.31,
        },
    ]
}
